yarnPath: .yarn/releases/yarn-4.3.1.cjs
defaultSemverRangePrefix: ""

packageExtensions:
  "@chromatic-com/storybook@1.6.1":
    dependencies:
      react: 18.3.1
  "@nextui-org/system@2.2.2":
    dependencies:
      "@nextui-org/theme": 2.2.6
      tailwindcss: 3.4.4
  "@sentry/nextjs@8.17.0":
    dependencies:
      react: 18.3.1
      "@opentelemetry/api": 1.9.0
      "@opentelemetry/core": 1.25.1
      "@opentelemetry/instrumentation": 0.52.1
      "@opentelemetry/sdk-trace-base": 1.25.1
      "@opentelemetry/semantic-conventions": 1.25.1
  "@storybook/addon-controls@8.2.1":
    dependencies:
      react: 18.3.1
      react-dom: 18.3.1
  "@storybook/addon-onboarding@8.2.1":
    dependencies:
      react: 18.3.1
  "@storybook/manager-api@8.2.1":
    dependencies:
      react: 18.3.1
      react-dom: 18.3.1
  "@typescript-eslint/utils@5.62.0":
    dependencies:
      typescript: 5.4.5
  "@typescript-eslint/utils@7.14.1":
    dependencies:
      typescript: 5.4.5
  "@typescript-eslint/utils@7.15.0":
    dependencies:
      typescript: 5.4.5
  "@typescript-eslint/utils@7.16.0":
    dependencies:
      typescript: 5.4.5
  "@typescript-eslint/utils@8.0.0-alpha.30":
    dependencies:
      typescript: 5.4.5
