services:
  client:
    container_name: client
    build:
      context: ./
      dockerfile: ./apps/client/Dockerfile
    restart: always
    env_file:
      - ./apps/client/.env
    ports:
      - 3000:3000
    environment:
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./apps/client:/app/apps/client
